name: Build and Test
on:
  push:
    branches:
      - heroku-test
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@heroku-test
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@heroku-test
        with:
          node-version: 16.13.1
      - name: Build, lint and test
        run: |
          yarn
          yarn test --watch=false --browsers=ChromeHeadless
          yarn build --prod
